version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-ap:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.api
    environment:
      PORT: 3000
      DB_HOST: postgres
      REDIS_HOST: redis
      HOME_REGION: ap-south-1
      OBSERVABILITY_SERVICE_NAME: api-ap
    depends_on:
      - postgres
      - redis

  api-eu:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.api
    environment:
      PORT: 3000
      DB_HOST: postgres
      REDIS_HOST: redis
      HOME_REGION: eu-west-1
      OBSERVABILITY_SERVICE_NAME: api-eu
    depends_on:
      - postgres
      - redis

  api-us:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.api
    environment:
      PORT: 3000
      DB_HOST: postgres
      REDIS_HOST: redis
      HOME_REGION: us-east-1
      OBSERVABILITY_SERVICE_NAME: api-us
    depends_on:
      - postgres
      - redis

  nginx-global:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.multi-region.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/waf.rules.conf:/etc/nginx/waf.rules.conf:ro
    depends_on:
      - api-ap
      - api-eu
      - api-us
